Repository missionpinball/mpf, pull requests merged in 2018-10, with the labels that each got.

#1238 add can_cancel option to opp rules
  mpf/platforms/opp/opp.py
  mpf/platforms/opp/opp_coil.py
  mpf/platforms/opp/opp_rs232_intf.py
  mpf/tests/test_OPP.py
Labels: Open Pinball Project

#1236 only reset drop target bank when a target is down
  mpf/devices/drop_target.py
  mpf/tests/test_DropTargets.py
Labels: new feature

#1239 add serial led support for PD-LED
  mpf/config_spec.yaml
  mpf/platforms/p3_roc.py
  mpf/platforms/p_roc.py
  mpf/platforms/p_roc_common.py
  mpf/platforms/p_roc_devices.py
Labels: Multimorphic, new feature

#1240 actually use poll_hz in lisy
  mpf/platforms/lisy/lisy.py
Labels: LISY

#1244 support game start and player add using events
  mpf/config_spec.yaml
  mpf/modes/attract/code/attract.py
  mpf/modes/game/code/game.py
  mpf/tests/machine_files/game/config/config.yaml
  mpf/tests/test_Game.py
Labels: new feature

#1247 Added mode_will_start to have a coding hook before the modes devices …
  mpf/core/mode.py
Labels: new feature

#1248 support external platforms via entry_points
  mpf/core/machine.py
Labels: new feature
