Repository missionpinball/mpf, pull requests merged in 2019-05, with the labels that each got.

#1356 allow newer fast firmwares
  mpf/platforms/fast/fast_serial_communicator.py
Labels: FAST Pinball, code refactor

#1357 allow settings for credit tiers
  mpf/config_spec.yaml
  mpf/core/placeholder_manager.py
  mpf/modes/credits/code/credits.py
  mpf/tests/machine_files/credits/config/config.yaml
Labels: new feature

#1358 use placeholders in tilt. fix #1031
  mpf/config_spec.yaml
  mpf/core/config_validator.py
  mpf/core/mode.py
  mpf/modes/credits/code/credits.py
  mpf/modes/high_score/code/high_score.py
  mpf/modes/tilt/code/tilt.py
  mpf/tests/machine_files/tilt/config/config.yaml
  mpf/tests/machine_files/tilt/config/config_mechanical_eject.yaml
  mpf/tests/machine_files/tilt/config/config_system_11_trough.yaml
  mpf/tests/machine_files/tilt/config/settings.yaml
  mpf/tests/machine_files/tilt/modes/tilt/config/tilt.yaml
Labels: new feature

#1364 add --vpx commandline option
  mpf/commands/game.py
Labels: new feature

#1365 Placeholder for state machine
  mpf/core/device_monitor.py
  mpf/core/placeholder_manager.py
  mpf/devices/state_machine.py
  mpf/tests/MpfDocTestCase.py
  mpf/tests/test_StateMachine.py
Labels: new feature

#1370 Generic system11
  mpf/config_spec.yaml
  mpf/mpfconfig.yaml
  mpf/platforms/snux.py
  mpf/platforms/system11.py
  mpf/tests/machine_files/lisy/config/config_system11.yaml
  mpf/tests/machine_files/p_roc/config/snux.yaml
  mpf/tests/machine_files/snux/config/config.yaml
  mpf/tests/test_Lisy.py
  mpf/tests/test_Snux.py
Labels: LISY, code refactor, new feature

#1372 Fix "enabled" value in placeholder for devices
  mpf/devices/ball_hold.py
  mpf/devices/multiball.py
  mpf/devices/multiball_lock.py
  mpf/tests/machine_files/ball_holds/config/test_ball_holds.yaml
  mpf/tests/machine_files/multiball/config/config.yaml
  mpf/tests/machine_files/multiball_locks/config/testDefault.yaml
  mpf/tests/machine_files/multiball_locks/modes/default/config/default.yaml
  mpf/tests/test_BallHold.py
  mpf/tests/test_MultiBall.py
  mpf/tests/test_MultiballLock.py
Labels: bug

#1376 improve error on empty number in all platforms
  mpf/core/platform.py
  mpf/devices/accelerometer.py
  mpf/devices/digital_output.py
  mpf/devices/driver.py
  mpf/devices/light.py
  mpf/devices/segment_display.py
  mpf/devices/servo.py
  mpf/devices/stepper.py
  mpf/devices/switch.py
  mpf/platforms/virtual.py
  mpf/tests/machine_files/snux/config/config.yaml
Labels: code refactor

#1379 Placeholders in show tokens
  mpf/config_players/show_player.py
  mpf/config_spec.yaml
  mpf/core/config_validator.py
  mpf/core/placeholder_manager.py
  mpf/tests/machine_files/shows/config/test_shows.yaml
  mpf/tests/test_Shows.py
Labels: new feature
