Repository missionpinball/mpf, pull requests merged in 2019-07, with the labels that each got.

#1388 Lisy segment displays
  mpf/core/clock.py
  mpf/core/mode.py
  mpf/core/mpf_controller.py
  mpf/core/platform.py
  mpf/core/player.py
  mpf/core/segment_mappings.py
  mpf/devices/light_group.py
  mpf/devices/score_reel.py
  mpf/devices/segment_display.py
  mpf/platforms/base_serial_communicator.py
  mpf/platforms/light_segment_displays.py
  mpf/platforms/lisy/lisy.py
  mpf/platforms/mypinballs/mypinballs.py
  mpf/platforms/p_roc.py
  mpf/platforms/virtual.py
  mpf/tests/machine_files/apc/config/config.yaml
  mpf/tests/test_LightSegmentDisplays.py
  mpf/tests/test_Lisy.py
  mpf/tests/test_SegmentMappings.py
  tools/convert_segments.py
Labels: code refactor, new feature

#1389 add tokens to slide_player
  mpf/config_spec.yaml
Labels: new feature

#1390 increase light throughput by 10%
  mpf/core/device_monitor.py
  mpf/core/light_controller.py
  mpf/core/machine.py
  mpf/core/placeholder_manager.py
  mpf/devices/light.py
Labels: code refactor

#1392 Tune shows and events
  mpf/assets/show.py
  mpf/config_players/plugin_player.py
  mpf/config_players/show_player.py
  mpf/core/config_player.py
  mpf/core/events.py
  mpf/core/placeholder_manager.py
  mpf/core/show_controller.py
  mpf/tests/MpfTestCase.py
  mpf/tests/machine_files/light_player/config/light_player.yaml
  mpf/tests/machine_files/light_player/shows/show_ext1.yaml
  mpf/tests/machine_files/light_player/shows/show_ext2.yaml
  mpf/tests/machine_files/light_player/shows/show_ext3.yaml
  mpf/tests/test_LightPlayer.py
Labels: code refactor

#1396 1190 modes in subfolders
  mpf/core/mode_controller.py
  mpf/tests/machine_files/mode_tests/config/test_modes.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/mode5/config/mode5.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/mode5/config/test.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/mode5/mode8/config/mode8.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/mode5/mode8/config/test.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/sub_mode/mode6/config/mode6.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/sub_mode/mode6/config/test.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/sub_mode/mode7/config/mode7.yaml
  mpf/tests/machine_files/mode_tests/modes/mode_in_sub_folder/sub_mode/mode7/config/test.yaml
  mpf/tests/test_Modes.py
Labels: code refactor, new feature

#1397 Refactor parsing out of hot path
  mpf/config_players/event_player.py
  mpf/config_players/light_player.py
  mpf/config_players/score_queue_player.py
  mpf/config_players/show_player.py
  mpf/config_players/variable_player.py
  mpf/core/assets.py
  mpf/core/bcp/bcp_client.py
  mpf/core/bcp/bcp_socket_client.py
  mpf/core/placeholder_manager.py
  mpf/core/rgb_color.py
  mpf/devices/light.py
  mpf/modes/carousel/code/carousel.py
  mpf/tests/test_PlaceholderManager.py
  mpf/tests/test_RGBColor.py
Labels: code refactor
