Repository missionpinball/mpf, pull requests merged in 2019-04, with the labels that each got.

#1330 always auto launch when the machine is tilted
  mpf/devices/ball_device/outgoing_balls_handler.py
  mpf/modes/tilt/code/tilt.py
  mpf/tests/machine_files/tilt/config/config_mechanical_eject.yaml
  mpf/tests/test_Tilt.py
Labels: new feature

#1341 Make ejecting from devices configurable in ball search.
  AUTHORS
  mpf/devices/ball_device/pulse_coil_ejector.py
  mpf/tests/machine_files/ball_search/config/no_eject.yaml
  mpf/tests/test_BallSearch.py
Labels: new feature

#1344 remove DelayRegistry since it is no longer needed with asyncio
  mpf/config_players/event_player.py
  mpf/config_players/flasher_player.py
  mpf/config_players/segment_display_player.py
  mpf/core/ball_controller.py
  mpf/core/ball_search.py
  mpf/core/custom_code.py
  mpf/core/delays.py
  mpf/core/machine.py
  mpf/core/mode.py
  mpf/core/scriptlet.py
  mpf/devices/autofire.py
  mpf/devices/ball_device/ball_device.py
  mpf/devices/ball_device/enable_coil_ejector.py
  mpf/devices/ball_save.py
  mpf/devices/combo_switch.py
  mpf/devices/digital_output.py
  mpf/devices/diverter.py
  mpf/devices/driver.py
  mpf/devices/drop_target.py
  mpf/devices/light.py
  mpf/devices/logic_blocks.py
  mpf/devices/magnet.py
  mpf/devices/multiball.py
  mpf/devices/playfield.py
  mpf/devices/score_reel.py
  mpf/devices/sequence_shot.py
  mpf/devices/servo.py
  mpf/devices/shot.py
  mpf/devices/stepper.py
  mpf/devices/timer.py
  mpf/platforms/rpi/rpi.py
  mpf/platforms/smart_virtual.py
  mpf/platforms/snux.py
  mpf/plugins/switch_player.py
  mpf/tests/test_EventManager.py
Labels: code refactor

#1343 Stop on nano reboot
  mpf/platforms/fast/fast.py
  mpf/tests/test_Fast.py
Labels: FAST Pinball, new feature

#1339 refactor text ui to use asciimatics widgets
  mpf/core/text_ui.py
Labels: code refactor

#1327 Separate event handlers from normal code
  mpf/config_players/coil_player.py
  mpf/config_spec.yaml
  mpf/core/device_manager.py
  mpf/core/enable_disable_mixin.py
  mpf/core/mode_device.py
  mpf/devices/achievement.py
  mpf/devices/achievement_group.py
  mpf/devices/autofire.py
  mpf/devices/ball_device/ball_device.py
  mpf/devices/ball_hold.py
  mpf/devices/ball_lock.py
  mpf/devices/ball_routing.py
  mpf/devices/ball_save.py
  mpf/devices/digital_output.py
  mpf/devices/diverter.py
  mpf/devices/driver.py
  mpf/devices/drop_target.py
  mpf/devices/dual_wound_coil.py
  mpf/devices/extra_ball.py
  mpf/devices/extra_ball_group.py
  mpf/devices/flipper.py
  mpf/devices/logic_blocks.py
  mpf/devices/magnet.py
  mpf/devices/motor.py
  mpf/devices/multiball.py
  mpf/devices/multiball_lock.py
  mpf/devices/playfield.py
  mpf/devices/playfield_transfer.py
  mpf/devices/sequence_shot.py
  mpf/devices/servo.py
  mpf/devices/shot.py
  mpf/devices/shot_group.py
  mpf/devices/stepper.py
  mpf/tests/test_DeviceManager.py
Labels: code refactor

#1347 Better shutdown and signal handlers
  mpf/commands/game.py
  mpf/core/bcp/bcp_transport.py
  mpf/core/machine.py
  mpf/core/text_ui.py
  mpf/platforms/p_roc_common.py
Labels: bug, code refactor

#1350 Fix count with physical only strategy
  mpf/core/machine.py
  mpf/devices/multiball_lock.py
  mpf/tests/machine_files/ball_routing/modes/mode1/config/mode1.yaml
  mpf/tests/machine_files/multiball_locks/modes/min_virtual_physical/config/min_virtual_physical.yaml
  mpf/tests/machine_files/multiball_locks/modes/no_virtual/config/no_virtual.yaml
  mpf/tests/machine_files/multiball_locks/modes/physical_only/config/physical_only.yaml
  mpf/tests/machine_files/multiball_locks/modes/virtual_only/config/virtual_only.yaml
  mpf/tests/test_BallRouting.py
  mpf/tests/test_MultiBall.py
  mpf/tests/test_MultiballLock.py
Labels: bug, code refactor

#1351 do not keep ball in outhole after tilt. fix #1335
  mpf/modes/tilt/code/tilt.py
  mpf/tests/machine_files/tilt/config/config_system_11_trough.yaml
  mpf/tests/test_Tilt.py
Labels: bug

#1354 add setting for free_play
  mpf/modes/credits/code/credits.py
  mpf/tests/machine_files/credits/config/config_freeplay.yaml
  mpf/tests/test_CreditsMode.py
Labels: new feature

#1352 do not depend on python asyncio internals. fix crash in bonus mode wi…
  mpf/core/delays.py
  mpf/tests/test_Delay.py
Labels: bug, code refactor
