Repository missionpinball/mpf, pull requests merged in 2019-06, with the labels that each got.

#1377 Bugfix multiball doublecounting
  mpf/devices/multiball_lock.py
  mpf/tests/machine_files/multiball_locks/config/config.yaml
  mpf/tests/machine_files/multiball_locks/modes/default/config/default.yaml
  mpf/tests/test_MultiballLock.py
Labels: bug

#1380 Logging with links
  mpf/config_spec.yaml
  mpf/core/logging.py
  mpf/core/platform.py
  mpf/core/switch_controller.py
  mpf/exceptions/ConfigFileError.py
  mpf/platforms/fadecandy.py
  mpf/platforms/fast/fast.py
  mpf/platforms/i2c_servo_controller.py
  mpf/platforms/lisy/lisy.py
  mpf/platforms/mma8451.py
  mpf/platforms/mypinballs/mypinballs.py
  mpf/platforms/openpixel.py
  mpf/platforms/opp/opp.py
  mpf/platforms/p_roc.py
  mpf/platforms/pololu/pololu_tic.py
  mpf/platforms/pololu_maestro.py
  mpf/platforms/rpi/rpi.py
  mpf/platforms/spike/spike.py
  mpf/tests/test_Config.py
  mpf/tests/test_ModesConfigValidation.py
Labels: code refactor, new feature

#1381 Support Conditional Carousel Items
  mpf/modes/carousel/code/carousel.py
  mpf/tests/machine_files/carousel/config/config.yaml
  mpf/tests/machine_files/carousel/modes/conditional_carousel/config/conditional_carousel.yaml
  mpf/tests/test_CarouselMode.py
Labels: new feature

#1387 fix #1382 and refactor enable attribue
  mpf/core/device_monitor.py
  mpf/core/enable_disable_mixin.py
  mpf/devices/ball_hold.py
  mpf/devices/ball_routing.py
  mpf/devices/multiball.py
  mpf/devices/multiball_lock.py
  mpf/devices/shot_group.py
  mpf/tests/test_MultiballLock.py
  mpf/tests/test_ShotGroups.py
  mpf/tests/test_Shots.py
Labels: code refactor, new feature
