Repository missionpinball/mpf, pull requests merged in 2019-11, with the labels that each got.

#1447 make high score suitable for dmd and lcd
  mpf/modes/high_score/config/high_score.yaml
Labels: code refactor

#1455 refactor config validation
  mpf/config_spec.yaml
  mpf/core/config_validator.py
  mpf/core/device_manager.py
  mpf/core/utility_functions.py
  mpf/devices/logic_blocks.py
Labels: code refactor

#1460 support spike fw 0.49+
  mpf/config_spec.yaml
  mpf/platforms/spike/spike.py
  mpf/tests/test_Spike.py
Labels: Stern Pinball, code refactor, new feature

#1463 Ball save dynamic values
  mpf/config_spec.yaml
  mpf/devices/ball_save.py
  mpf/tests/machine_files/ball_save/config/config.yaml
  mpf/tests/test_BallSave.py
Labels: breaking change, new feature

#1464 Auto-detect FAST device ports
  mpf/platforms/fast/fast.py
Labels: FAST Pinball, new feature

#1466 improve debugging in lisy + optional length is only payload
  mpf/platforms/lisy/lisy.py
Labels: LISY, code refactor
