Repository missionpinball/mpf, pull requests merged in 2020-01, with the labels that each got.

#1485 prevent duplicate handlers
  mpf/core/bcp/bcp_transport.py
  mpf/tests/test_PluginConfigPlayer.py
Labels: bug

#1486 prevent duplicate handlers
  mpf/core/bcp/bcp_transport.py
  mpf/tests/test_PluginConfigPlayer.py
Labels: backport, bug

#1484 Add pin2dmd
  mpf/mpfconfig.yaml
  mpf/platforms/pin2dmd.py
  mpf/platforms/smartmatrix.py
Labels: new feature

#1482 Allow Fast RGB crashes to be ignored
  mpf/config_spec.yaml
  mpf/platforms/fast/fast.py
  mpf/tests/test_Fast.py
Labels: FAST Pinball

#1487 add service mode menu entry for software updates
  mpf/modes/service/code/service.py
  mpf/modes/service/config/service.yaml
  mpf/tests/machine_files/service_mode/config/config.yaml
Labels: new feature

#1488 move _done callback into Util to reduce duplications
  mpf/core/assets.py
  mpf/core/async_mode.py
  mpf/core/ball_controller.py
  mpf/core/bcp/bcp_transport.py
  mpf/core/events.py
  mpf/core/light_controller.py
  mpf/core/platform.py
  mpf/core/platform_batch_light_system.py
  mpf/core/utility_functions.py
  mpf/devices/ball_device/ball_device_state_handler.py
  mpf/devices/ball_device/physical_ball_counter.py
  mpf/devices/score_queue.py
  mpf/devices/score_reel.py
  mpf/devices/stepper.py
  mpf/platforms/base_serial_communicator.py
  mpf/platforms/fast/fast_serial_communicator.py
  mpf/platforms/interfaces/segment_display_platform_interface.py
  mpf/platforms/lisy/lisy.py
  mpf/platforms/mma8451.py
  mpf/platforms/opp/opp.py
  mpf/platforms/p_roc_common.py
  mpf/platforms/pin2dmd.py
  mpf/platforms/pololu/pololu_ticcmd_wrapper.py
  mpf/platforms/rpi/rpi.py
  mpf/platforms/smartmatrix.py
  mpf/platforms/spi_bit_bang.py
  mpf/platforms/spike/spike.py
  mpf/platforms/step_stick.py
Labels: code refactor

#1491 support RBG and 192x64 Pin2DMD panels
  mpf/config_spec.yaml
  mpf/platforms/pin2dmd.py
Labels: new feature
